# Generated by Django 4.1 on 2024-08-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kendaraan',
            fields=[
                ('id_kendaraan', models.AutoField(primary_key=True, serialize=False)),
                ('nama_sopir', models.CharField(blank=True, max_length=255, null=True)),
                ('plat_kendaraan', models.CharField(blank=True, max_length=255, null=True)),
                ('jenis_kendaraan', models.CharField(blank=True, max_length=255, null=True)),
                ('telepon', models.CharField(blank=True, max_length=255, null=True)),
                ('id_sopir', models.IntegerField(blank=True, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
