# Generated by Django 4.1 on 2024-08-01 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JadwalOperasiAngkutan',
            fields=[
                ('id_jadwal', models.AutoField(primary_key=True, serialize=False)),
                ('jam_kedatangan', models.CharField(blank=True, max_length=255, null=True)),
                ('jam_keberangkatan', models.CharField(blank=True, max_length=255, null=True)),
                ('route', models.TextField(blank=True, null=True)),
                ('id_kendaraan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.kendaraan')),
            ],
        ),
    ]
