# Generated by Django 4.1 on 2024-08-01 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_jadwaloperasiangkutan'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('petugas', 'petugas'), ('sopir', 'sopir'), ('penumpang', 'penumpang')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id_tarif', models.AutoField(primary_key=True, serialize=False)),
                ('tarif', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('route', models.TextField(blank=True, null=True)),
                ('id_kendaraan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.kendaraan')),
            ],
        ),
        migrations.CreateModel(
            name='Penumpang',
            fields=[
                ('id_penumpang', models.AutoField(primary_key=True, serialize=False)),
                ('nama_penumpang', models.CharField(blank=True, max_length=255, null=True)),
                ('jenis_kelamin', models.CharField(blank=True, max_length=255, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('telepon', models.CharField(blank=True, max_length=255, null=True)),
                ('id_kendaraan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.kendaraan')),
            ],
        ),
    ]
