# Generated by Django 4.1 on 2024-08-02 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_user_tarif_penumpang'),
    ]

    operations = [
        migrations.CreateModel(
            name='Angkutan',
            fields=[
                ('id_angkutan', models.AutoField(primary_key=True, serialize=False)),
                ('nama_angkutan', models.CharField(blank=True, max_length=255, null=True)),
                ('jenis_angkutan', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id_jadwal', models.AutoField(primary_key=True, serialize=False)),
                ('waktu_berangkat', models.DateField(blank=True, null=True)),
                ('id_angkutan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.angkutan')),
            ],
        ),
        migrations.CreateModel(
            name='Kios',
            fields=[
                ('id_kios', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kios', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rute',
            fields=[
                ('id_rute', models.AutoField(primary_key=True, serialize=False)),
                ('asal', models.CharField(blank=True, max_length=255, null=True)),
                ('tujuan', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id_terminal', models.AutoField(primary_key=True, serialize=False)),
                ('nama_terminal', models.CharField(blank=True, max_length=255, null=True)),
                ('lokasi', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='jadwaloperasiangkutan',
            name='id_kendaraan',
        ),
        migrations.RemoveField(
            model_name='penumpang',
            name='id_kendaraan',
        ),
        migrations.RemoveField(
            model_name='tarif',
            name='id_kendaraan',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='JadwalOperasiAngkutan',
        ),
        migrations.DeleteModel(
            name='Kendaraan',
        ),
        migrations.DeleteModel(
            name='Penumpang',
        ),
        migrations.DeleteModel(
            name='Tarif',
        ),
        migrations.AddField(
            model_name='kios',
            name='id_terminal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.terminal'),
        ),
        migrations.AddField(
            model_name='jadwal',
            name='id_rute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.rute'),
        ),
        migrations.AddField(
            model_name='jadwal',
            name='id_terminal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.terminal'),
        ),
    ]
