# Generated by Django 4.1 on 2024-08-02 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_angkutan_jadwal_kios_rute_terminal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penumpang',
            fields=[
                ('id_penumpang', models.AutoField(primary_key=True, serialize=False)),
                ('jumlah_naik', models.IntegerField(blank=True, null=True)),
                ('jumlah_turun', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='jadwal',
            name='id_penumpang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.penumpang'),
        ),
    ]
