# Generated by Django 4.1 on 2024-08-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_remove_jadwal_id_penumpang_angkutan_id_penumpang'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadwal',
            name='jam_berangkat',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jadwal',
            name='jam_masuk',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
