# Generated by Django 4.1 on 2024-08-02 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_jadwal_jam_berangkat_jadwal_jam_masuk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jadwal',
            old_name='jam_berangkat',
            new_name='jam_keluar',
        ),
    ]
