# Generated by Django 4.1 on 2024-08-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_rename_jam_berangkat_jadwal_jam_keluar'),
    ]

    operations = [
        migrations.AddField(
            model_name='angkutan',
            name='plat_nomor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
