# Generated by Django 4.1 on 2024-08-02 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_angkutan_plat_nomor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='angkutan',
            old_name='nama_angkutan',
            new_name='nama_sopir',
        ),
    ]
