# Generated by Django 4.1 on 2024-08-03 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_rename_nama_angkutan_angkutan_nama_sopir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='angkutan',
            name='id_penumpang',
        ),
        migrations.AddField(
            model_name='penumpang',
            name='id_angkutan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.angkutan'),
        ),
    ]
