# Generated by Django 4.1 on 2024-08-05 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_remove_angkutan_id_penumpang_penumpang_id_angkutan'),
    ]

    operations = [
        migrations.AddField(
            model_name='angkutan',
            name='id_rute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.rute'),
        ),
    ]
