# Generated by Django 4.1 on 2024-08-05 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_angkutan_id_rute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jadwal',
            name='id_rute',
        ),
    ]
