# Generated by Django 4.1 on 2024-08-07 08:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_remove_jadwal_id_rute'),
    ]

    operations = [
        migrations.AddField(
            model_name='penumpang',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
