# Generated by Django 4.1 on 2024-08-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_angkutan_keterangan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penumpang',
            name='created_at',
        ),
        migrations.AddField(
            model_name='penumpang',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
