# Generated by Django 4.1 on 2024-08-08 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_penumpang_created_at_penumpang_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penumpang',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='penumpang',
            name='updated_at',
        ),
    ]
