# Generated by Django 4.1 on 2024-08-08 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_remove_penumpang_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='penumpang',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='penumpang',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
