# Generated by Django 4.1 on 2024-08-08 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0021_jadwal_created_at_jadwal_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jadwal',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='jadwal',
            name='updated_at',
        ),
    ]
