# Generated by Django 4.1 on 2024-08-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0023_jadwal_created_at_jadwal_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='penumpang',
            name='waktu_berangkat',
            field=models.DateField(blank=True, null=True),
        ),
    ]
