# Generated by Django 4.1 on 2024-08-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0024_penumpang_waktu_berangkat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeri',
            fields=[
                ('id_galeri', models.AutoField(primary_key=True, serialize=False)),
                ('judul', models.CharField(blank=True, max_length=255, null=True)),
                ('deskripsi', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
