# Generated by Django 4.1 on 2024-08-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0025_galeri'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeri',
            name='file_upload',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
