# Generated by Django 4.1 on 2024-08-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0026_galeri_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeri',
            name='file_upload',
            field=models.ImageField(blank=True, null=True, upload_to='galeri/'),
        ),
    ]
