# Generated by Django 4.1 on 2024-08-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0027_alter_galeri_file_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadwal',
            name='tarif',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jadwal',
            name='telepon',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
