# Generated by Django 4.1 on 2024-08-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0028_jadwal_tarif_jadwal_telepon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jadwal',
            name='tarif',
        ),
        migrations.RemoveField(
            model_name='jadwal',
            name='telepon',
        ),
        migrations.AddField(
            model_name='angkutan',
            name='tarif',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='angkutan',
            name='telepon',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
