# Generated by Django 4.1 on 2024-08-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0029_remove_jadwal_tarif_remove_jadwal_telepon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angkutan',
            name='tarif',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='angkutan',
            name='telepon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
