# Generated by Django 4.1 on 2024-08-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0030_alter_angkutan_tarif_alter_angkutan_telepon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penumpang',
            name='jumlah_naik',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='penumpang',
            name='jumlah_turun',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
