# Generated by Django 4.1 on 2024-08-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0031_alter_penumpang_jumlah_naik_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penumpang',
            name='jumlah_naik',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='penumpang',
            name='jumlah_turun',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
