# Generated by Django 4.1 on 2024-08-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0032_alter_penumpang_jumlah_naik_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saran',
            fields=[
                ('id_saran', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(blank=True, max_length=255, null=True)),
                ('telepon', models.IntegerField(blank=True, null=True)),
                ('subjek', models.CharField(blank=True, max_length=255, null=True)),
                ('pesan', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
