# Generated by Django 4.1 on 2024-08-19 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0034_galeri_created_at_saran_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id_kategori', models.AutoField(primary_key=True, serialize=False)),
                ('kategori', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trayek',
            fields=[
                ('id_trayek', models.AutoField(primary_key=True, serialize=False)),
                ('jenis_trayek', models.CharField(blank=True, max_length=255, null=True)),
                ('jarak', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_kategori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.kategori')),
                ('id_rute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.rute')),
            ],
        ),
    ]
