# Generated by Django 4.1 on 2024-08-19 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0036_trayek_jumlah_armada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trayek',
            name='id_kategori',
        ),
        migrations.DeleteModel(
            name='Kategori',
        ),
    ]
