# Generated by Django 4.1 on 2024-08-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0038_kategori_trayek_id_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trayek',
            name='jumlah_armada',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
