# Generated by Django 4.1 on 2024-08-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0039_alter_trayek_jumlah_armada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trayek',
            name='jumlah_armada',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
