# Generated by Django 4.1 on 2024-08-24 14:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0042_alter_trayek_jarak_alter_trayek_jumlah_armada'),
    ]

    operations = [
        migrations.AddField(
            model_name='rute',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
