# Generated by Django 4.1 on 2024-10-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0043_rute_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='angkutan',
            name='rangka_mesin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
